application: pro-soc-client
version: 1
runtime: php55
api_version: 1

handlers:

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /user.php
  script: user.php

- url: /log-in.php
  script: log-in.php

- url: /log-out.php
  script: log-out.php
  
- url: /upload_handler.php
  script: upload_handler.php

- url: /loginvalidation.php
  script: loginvalidation.php

- url: /sign-up.html
  static_files: sign-up.html
  upload: sign-up.html
 
- url: /.*
  script: index.html
  
- url: /script
  static_dir: script

